# Form implementation generated from reading ui file 'prompt_student_details.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PromptStudentDetails(object):
    def setupUi(self, PromptStudentDetails):
        PromptStudentDetails.setObjectName("PromptStudentDetails")
        PromptStudentDetails.resize(400, 300)
        self.gridLayout_2 = QtWidgets.QGridLayout(PromptStudentDetails)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=PromptStudentDetails)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=PromptStudentDetails)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=PromptStudentDetails)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=PromptStudentDetails)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_numberOfExamsTaken = QtWidgets.QLabel(parent=PromptStudentDetails)
        self.label_numberOfExamsTaken.setText("")
        self.label_numberOfExamsTaken.setObjectName("label_numberOfExamsTaken")
        self.gridLayout.addWidget(self.label_numberOfExamsTaken, 1, 1, 1, 1)
        self.label_averageGrade = QtWidgets.QLabel(parent=PromptStudentDetails)
        self.label_averageGrade.setText("")
        self.label_averageGrade.setObjectName("label_averageGrade")
        self.gridLayout.addWidget(self.label_averageGrade, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=PromptStudentDetails)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(PromptStudentDetails)
        self.buttonBox.rejected.connect(PromptStudentDetails.reject) # type: ignore
        self.buttonBox.accepted.connect(PromptStudentDetails.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PromptStudentDetails)

    def retranslateUi(self, PromptStudentDetails):
        _translate = QtCore.QCoreApplication.translate
        PromptStudentDetails.setWindowTitle(_translate("PromptStudentDetails", "Student Details"))
        self.label_2.setText(_translate("PromptStudentDetails", "Number of Exams taken"))
        self.label.setText(_translate("PromptStudentDetails", "Student Name"))
        self.label_3.setText(_translate("PromptStudentDetails", "Average Grade"))
