# Form implementation generated from reading ui file 'prompt_add_exam.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_prompt_addExam(object):
    def setupUi(self, prompt_addExam):
        prompt_addExam.setObjectName("prompt_addExam")
        prompt_addExam.resize(400, 300)
        self.gridLayout_2 = QtWidgets.QGridLayout(prompt_addExam)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(parent=prompt_addExam)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.input_examName = QtWidgets.QLineEdit(parent=prompt_addExam)
        self.input_examName.setObjectName("input_examName")
        self.gridLayout.addWidget(self.input_examName, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=prompt_addExam)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=prompt_addExam)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.input_maxPoints = QtWidgets.QLineEdit(parent=prompt_addExam)
        self.input_maxPoints.setObjectName("input_maxPoints")
        self.gridLayout.addWidget(self.input_maxPoints, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=prompt_addExam)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.input_ptsFor6 = QtWidgets.QLineEdit(parent=prompt_addExam)
        self.input_ptsFor6.setObjectName("input_ptsFor6")
        self.gridLayout.addWidget(self.input_ptsFor6, 4, 1, 1, 1)
        self.input_computationStrategy = QtWidgets.QComboBox(parent=prompt_addExam)
        self.input_computationStrategy.setObjectName("input_computationStrategy")
        self.gridLayout.addWidget(self.input_computationStrategy, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=prompt_addExam)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.input_category = QtWidgets.QComboBox(parent=prompt_addExam)
        self.input_category.setObjectName("input_category")
        self.gridLayout.addWidget(self.input_category, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=prompt_addExam)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(prompt_addExam)
        self.buttonBox.accepted.connect(prompt_addExam.accept) # type: ignore
        self.buttonBox.rejected.connect(prompt_addExam.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(prompt_addExam)

    def retranslateUi(self, prompt_addExam):
        _translate = QtCore.QCoreApplication.translate
        prompt_addExam.setWindowTitle(_translate("prompt_addExam", "Add New Exam"))
        self.label_4.setText(_translate("prompt_addExam", "Points needed for 6"))
        self.input_examName.setToolTip(_translate("prompt_addExam", "Input name of exam (e.g. essaie 1)"))
        self.input_examName.setPlaceholderText(_translate("prompt_addExam", "Essaie 1"))
        self.label.setText(_translate("prompt_addExam", "Name"))
        self.label_2.setText(_translate("prompt_addExam", "Computation Strategy"))
        self.input_maxPoints.setToolTip(_translate("prompt_addExam", "Maximal possible points"))
        self.input_maxPoints.setPlaceholderText(_translate("prompt_addExam", "25"))
        self.label_3.setText(_translate("prompt_addExam", "Maximum Points"))
        self.input_ptsFor6.setPlaceholderText(_translate("prompt_addExam", "22.5"))
        self.input_computationStrategy.setToolTip(_translate("prompt_addExam", "Select Computation of Grades (e.g. linear, curve fitting, ...)"))
        self.label_5.setText(_translate("prompt_addExam", "Category"))
