# Form implementation generated from reading ui file 'ui/ui_prompt_add_category.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_add_category(object):
    def setupUi(self, add_category):
        add_category.setObjectName("add_category")
        add_category.resize(390, 304)
        self.gridLayout_2 = QtWidgets.QGridLayout(add_category)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=add_category)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.input_categoryName = QtWidgets.QLineEdit(parent=add_category)
        self.input_categoryName.setObjectName("input_categoryName")
        self.gridLayout.addWidget(self.input_categoryName, 0, 1, 1, 1)
        self.input_weight = QtWidgets.QLineEdit(parent=add_category)
        self.input_weight.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhFormattedNumbersOnly)
        self.input_weight.setObjectName("input_weight")
        self.gridLayout.addWidget(self.input_weight, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=add_category)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=add_category)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.input_gradingType = QtWidgets.QComboBox(parent=add_category)
        self.input_gradingType.setObjectName("input_gradingType")
        self.gridLayout.addWidget(self.input_gradingType, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=add_category)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(add_category)
        self.buttonBox.accepted.connect(add_category.accept) # type: ignore
        self.buttonBox.rejected.connect(add_category.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(add_category)

    def retranslateUi(self, add_category):
        _translate = QtCore.QCoreApplication.translate
        add_category.setWindowTitle(_translate("add_category", "Add Category"))
        self.label_2.setText(_translate("add_category", "Weight"))
        self.input_categoryName.setToolTip(_translate("add_category", "Insert name for category (e.g. essai, oral, ...)"))
        self.input_categoryName.setPlaceholderText(_translate("add_category", "grammaire"))
        self.input_weight.setToolTip(_translate("add_category", "Input weight of this category (value between 0 and 1)"))
        self.input_weight.setPlaceholderText(_translate("add_category", "0.25"))
        self.label.setText(_translate("add_category", "Name"))
        self.label_3.setText(_translate("add_category", "Grading type"))
